# Generated by Django 5.0.3 on 2024-03-19 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatusRosterApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('cluster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StatusRosterApp.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=4)),
                ('role', models.CharField(choices=[('A', 'Admin'), ('U', 'User')], max_length=1)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StatusRosterApp.member')),
            ],
        ),
    ]
