# Generated by Django 5.0.3 on 2024-03-19 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatusRosterApp', '0002_member_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PL', 'Planned Leave'), ('TA', 'Training Allowance'), ('CO', 'Compulsary Off'), ('HD', 'Half Day Leave'), ('FL', 'Floating Leave'), ('SL', 'Sick Leave'), ('HL', 'Hospitalizatoin Leave'), ('ML', 'Maternity Leave'), ('GS', 'General Shift'), ('SS', 'Second Shift'), ('OC', 'On Call'), ('HC', 'Holiday on Call'), ('GH', 'General Holiday')], max_length=2)),
                ('date', models.DateField()),
                ('comment', models.TextField(max_length=100)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StatusRosterApp.member')),
            ],
        ),
    ]
