# Generated by Django 5.0.3 on 2024-03-19 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatusRosterApp', '0004_alter_member_options_alter_member_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='cluster_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StatusRosterApp.cluster'),
        ),
    ]
