# Generated by Django 5.0.3 on 2024-03-19 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatusRosterApp', '0005_alter_member_cluster_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('roster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StatusRosterApp.roster')),
            ],
        ),
    ]
