# Generated by Django 5.0.3 on 2024-03-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatusRosterApp', '0006_alter_roster_id_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='name',
            field=models.CharField(default='cluster', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cluster',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
