# Generated by Django 5.0.3 on 2024-04-01 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatusRosterApp', '0008_alter_roster_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('M', 'Manager'), ('U', 'User')], max_length=1),
        ),
        migrations.AlterField(
            model_name='roster',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StatusRosterApp.status'),
        ),
    ]
