# Generated by Django 5.0.3 on 2024-04-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StatusRosterApp', '0009_status_alter_member_role_alter_roster_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
